"use client";

import { useCallback, useEffect, useState, type ReactNode } from "react";
import { useParams } from "next/navigation";

import { BriefingSign } from "@/components/borrower/BriefingSign";
import { ComputationSign } from "@/components/borrower/ComputationSign";
import { LoanActivePanel } from "@/components/borrower/LoanActivePanel";
import { ReleaseDocSign } from "@/components/borrower/ReleaseDocSign";
import { ApplicantProfileFields } from "@/components/borrowers/ApplicantProfileFields";
import {
  NegotiationLog,
  type NegotiationLogMessage,
} from "@/components/negotiation/NegotiationLog";
import { AutofillOverlay } from "@/components/dev/AutofillOverlay";
import {
  Alert,
  Badge,
  Breadcrumbs,
  Button,
  Card,
  ConfirmDialog,
  Modal,
  PageHeader,
  Spinner,
} from "@/components/ui";
import { BorrowerStatusTimeline } from "@/components/borrower/BorrowerStatusTimeline";
import { DocumentChecklist } from "@/components/DocumentChecklist";
import {
  formatStatusLabel,
  statusBadgeVariant,
  type StatusHistoryEntry,
} from "@/lib/applications/status";
import {
  borrowerAppFocus,
  borrowerAppPageDescription,
  borrowerAppPageTitle,
  docsUploadPercent,
  formatBlockerLabel,
  nextStepGuidance,
} from "@/lib/borrowers/home";
import type { BorrowerProfile } from "@/lib/borrowers/types";
import { fakeBorrowerProfile } from "@/lib/dev/fake-data";
import {
  allAutoGeneratedSlugs,
  releaseStagesForPaths,
  type ReleasePath,
} from "@/lib/lra/constants";

function isReleasePath(value: unknown): value is ReleasePath {
  return value === "with_pdc" || value === "without_pdc";
}

function signingStageTitle(stage: string): string {
  if (stage === "signing_with_pdc") {
    return "Supporting release uploads (with PDC)";
  }
  if (stage === "signing_without_pdc") {
    return "Supporting release uploads (without PDC)";
  }
  return "Supporting release uploads";
}

type TimelineEntry = StatusHistoryEntry & { label?: string };

type ApplicationDetail = {
  id: string;
  applicationNo: string | null;
  status: string;
  statusLabel: string;
  blocker: string | null;
  isReloan: boolean;
  createdAt: string;
  updatedAt: string;
  timeline: TimelineEntry[];
  segment: "seafarer" | "sme";
  entityType: "individual" | "corporate" | null;
};

type DocsSummary = {
  required: number;
  uploaded: number;
  complete: number;
};

type ComputationSummary = {
  id: string;
  inputMode: string;
  principal: number;
  netReleased: number;
  totalLoan: number;
  monthlyAmortization: number;
  lineItems: Array<{ key: string; label: string; amount: number }>;
  signedAt: string | null;
  loanTypeName: string | null;
};

function formatMoney(value: number) {
  return value.toLocaleString("en-PH", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-PH", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatDateTime(value: string) {
  return new Date(value).toLocaleString("en-PH", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export default function BorrowerApplicationPage() {
  const params = useParams();
  const applicationId = params.id as string;

  const [application, setApplication] = useState<ApplicationDetail | null>(
    null,
  );
  const [borrowerId, setBorrowerId] = useState<string | null>(null);
  const [profile, setProfile] = useState<BorrowerProfile | null>(null);
  const [showApplicationForm, setShowApplicationForm] = useState(false);
  const [savingProfile, setSavingProfile] = useState(false);
  const [profileError, setProfileError] = useState<string | null>(null);
  const [computation, setComputation] = useState<ComputationSummary | null>(
    null,
  );
  const [negotiationStatus, setNegotiationStatus] = useState<string | null>(
    null,
  );
  const [negotiationMessages, setNegotiationMessages] = useState<
    NegotiationLogMessage[]
  >([]);
  const [releasePaths, setReleasePaths] = useState<ReleasePath[]>([]);
  const [docsSummary, setDocsSummary] = useState<DocsSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showSubmitConfirm, setShowSubmitConfirm] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const load = useCallback(
    async (opts?: { silent?: boolean }) => {
      if (!opts?.silent) setLoading(true);
      setError(null);
      try {
        const [appRes, profileRes, compRes, releaseRes, checklistRes] =
          await Promise.all([
            fetch(`/api/borrower/applications/${applicationId}`),
            fetch("/api/borrower/profile"),
            fetch(`/api/borrower/applications/${applicationId}/computation`),
            fetch(
              `/api/borrower/applications/${applicationId}/release-documents`,
            ),
            fetch(
              `/api/borrower/applications/${applicationId}/checklist?stage=intake`,
            ),
          ]);
        if (!appRes.ok) throw new Error("Failed to load application");
        if (!profileRes.ok) throw new Error("Failed to load profile");
        const appData = (await appRes.json()) as {
          application: ApplicationDetail;
        };
        const profileData = (await profileRes.json()) as {
          profile: BorrowerProfile;
        };
        if (compRes.ok) {
          const compData = (await compRes.json()) as {
            computation: ComputationSummary | null;
            negotiation: { status: string } | null;
            negotiationMessages?: NegotiationLogMessage[];
          };
          setComputation(compData.computation);
          setNegotiationStatus(compData.negotiation?.status ?? null);
          setNegotiationMessages(compData.negotiationMessages ?? []);
        } else {
          setComputation(null);
          setNegotiationStatus(null);
          setNegotiationMessages([]);
        }
        if (releaseRes.ok) {
          const releaseData = (await releaseRes.json()) as {
            releaseFile: { releasePaths: unknown } | null;
          };
          const pathsRaw = releaseData.releaseFile?.releasePaths;
          setReleasePaths(
            (Array.isArray(pathsRaw) ? pathsRaw : []).filter(isReleasePath),
          );
        } else {
          setReleasePaths([]);
        }
        if (checklistRes.ok) {
          const checklistData = (await checklistRes.json()) as {
            summary: {
              required: number;
              uploaded: number;
              complete: number;
            };
          };
          setDocsSummary({
            required: checklistData.summary.required,
            uploaded: checklistData.summary.uploaded,
            complete: checklistData.summary.complete,
          });
        } else {
          setDocsSummary(null);
        }
        setApplication(appData.application);
        setBorrowerId(profileData.profile.id);
        setProfile(profileData.profile);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load");
      } finally {
        if (!opts?.silent) setLoading(false);
      }
    },
    [applicationId],
  );

  useEffect(() => {
    void load();
  }, [load]);

  async function handleSaveApplicationForm() {
    if (!profile) return;
    setSavingProfile(true);
    setProfileError(null);
    try {
      const res = await fetch("/api/borrower/profile", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          firstName: profile.firstName,
          middleName: profile.middleName,
          lastName: profile.lastName,
          suffix: profile.suffix,
          dateOfBirth: profile.dateOfBirth,
          placeOfBirth: profile.placeOfBirth,
          citizenship: profile.citizenship,
          civilStatus: profile.civilStatus,
          gender: profile.gender,
          mobilePhone: profile.mobilePhone,
          landline: profile.landline,
          presentAddress: profile.presentAddress,
          permanentAddress: profile.permanentAddress,
          manningAgency: profile.manningAgency,
          financial: profile.financial,
          allottee: profile.allottee,
          picWork: profile.picWork,
          businessInfo: profile.businessInfo,
          dependents: profile.dependents,
          references: profile.references,
          profileData: profile.profileData,
        }),
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => null)) as {
          error?: string;
        } | null;
        throw new Error(body?.error ?? "Failed to save application form");
      }
      setShowApplicationForm(false);
      await load({ silent: true });
    } catch (err) {
      setProfileError(
        err instanceof Error ? err.message : "Failed to save application form",
      );
    } finally {
      setSavingProfile(false);
    }
  }

  async function handleSubmitApplication() {
    setSubmitting(true);
    try {
      const res = await fetch(
        `/api/borrower/applications/${applicationId}/submit`,
        { method: "POST" },
      );
      const body = (await res.json().catch(() => null)) as {
        error?: string;
      } | null;
      if (!res.ok) {
        throw new Error(body?.error ?? "Failed to submit application");
      }
      setShowSubmitConfirm(false);
      await load({ silent: true });
    } catch (err) {
      setShowSubmitConfirm(false);
      setError(
        err instanceof Error ? err.message : "Failed to submit application",
      );
    } finally {
      setSubmitting(false);
    }
  }

  if (loading) return <Spinner />;
  if (!application || !borrowerId) {
    return <Alert>Application not found.</Alert>;
  }

  const focus = borrowerAppFocus(application.status);
  const signingStages = releaseStagesForPaths(releasePaths);
  const inReleaseFlow = [
    "lra_pending",
    "release_signing",
    "release_briefing",
    "release_ready",
    "released",
  ].includes(application.status);
  const showReleaseSections = [
    "lra_pending",
    "release_signing",
    "release_briefing",
    "release_ready",
    "released",
    "closed",
    "loan_active",
  ].includes(application.status);

  const crumbLabel =
    application.applicationNo ?? `Application ${applicationId.slice(0, 8)}…`;
  const pageTitle = borrowerAppPageTitle(application.status);
  const pageDescription = borrowerAppPageDescription({
    status: application.status,
    applicationNo: application.applicationNo,
  });
  const blockerLabel = formatBlockerLabel(application.blocker);
  const docsPct =
    docsSummary && docsSummary.required > 0
      ? docsUploadPercent({
          uploaded: docsSummary.uploaded,
          required: docsSummary.required,
        })
      : null;
  const guidance = nextStepGuidance({
    status: application.status,
    blocker: application.blocker,
    docsUploaded: docsSummary?.uploaded,
    docsRequired: docsSummary?.required,
  });
  const recentHistory = [...(application.timeline ?? [])]
    .sort((a, b) => String(b.at).localeCompare(String(a.at)))
    .slice(0, 3);

  const isDraft = application.status === "draft";
  const canSubmit = isDraft;

  const reload = () => void load({ silent: true });

  const intakeChecklist = (
    <div key="intake" className="flex flex-col gap-6">
      <Card className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="font-display text-lg font-semibold text-navy-900">
            Application Form
          </h2>
          <p className="text-sm text-ink-500">
            Fill this out digitally — replaces the scanned Credit
            Application Form.
          </p>
        </div>
        <Button
          type="button"
          variant="secondary"
          onClick={() => setShowApplicationForm(true)}
        >
          Edit application form
        </Button>
      </Card>

      {profile ? (
        <Modal
          open={showApplicationForm}
          title="Application Form"
          onClose={() => setShowApplicationForm(false)}
          className="!max-w-4xl"
          footer={
            <Button loading={savingProfile} onClick={() => void handleSaveApplicationForm()}>
              Save application form
            </Button>
          }
        >
          {profileError ? (
            <div className="mb-4">
              <Alert>{profileError}</Alert>
            </div>
          ) : null}
          <div className="max-h-[65vh] overflow-y-auto pr-1">
            <ApplicantProfileFields
              profile={profile}
              onChange={setProfile}
              segment={application?.segment}
              entityType={application?.entityType}
            />
          </div>
        </Modal>
      ) : null}

      <DocumentChecklist
        applicationId={application.id}
        borrowerId={borrowerId}
        stage="intake"
        title="Intake documents"
        description="Upload the required application documents — your CSA reviews and confirms each file."
        excludeSlugs={["clearance_form"]}
        defaultCollapsed={
          focus === "documents" ? false : inReleaseFlow ? true : "auto"
        }
        onUploadComplete={reload}
      />
    </div>
  );

  const termsSection = (
    // ComputationSign and NegotiationLog each already carry their own
    // Card mb-6 — a gap-6 parent (the pattern used elsewhere on this page,
    // e.g. intakeChecklist) would double the space between them. No gap
    // class here; the children's own margins do the spacing.
    <div key="terms" className="flex flex-col">
      <ComputationSign
        applicationId={application.id}
        applicationStatus={application.status}
        negotiationStatus={negotiationStatus}
        computation={computation}
        onSigned={reload}
      />
      {computation ? (
        <NegotiationLog
          messages={negotiationMessages}
          viewerRole="borrower"
          canPost={
            negotiationStatus === "awaiting_signature" ||
            negotiationStatus === "negotiating"
          }
          onPost={async (body) => {
            const res = await fetch(
              `/api/borrower/applications/${application.id}/negotiation-messages`,
              {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ body }),
              },
            );
            if (!res.ok) {
              const data = (await res.json().catch(() => null)) as {
                error?: string;
              } | null;
              throw new Error(data?.error ?? "Failed to send");
            }
            reload();
          }}
        />
      ) : null}
    </div>
  );

  const releaseSection = showReleaseSections ? (
    <div key="release" className="flex flex-col gap-6">
      <ReleaseDocSign applicationId={application.id} onSigned={reload} />
      <BriefingSign applicationId={application.id} onSigned={reload} />
      {inReleaseFlow
        ? signingStages.map((stage) => (
            <DocumentChecklist
              key={stage}
              applicationId={application.id}
              borrowerId={borrowerId}
              stage={stage}
              title={signingStageTitle(stage)}
              description="Upload supporting files for this release path (not the auto-generated PDFs)."
              excludeSlugs={[...allAutoGeneratedSlugs()]}
              onUploadComplete={reload}
            />
          ))
        : null}
    </div>
  ) : null;

  const loanSection = (
    <LoanActivePanel
      key="loan"
      applicationId={application.id}
      applicationStatus={application.status}
    />
  );

  const orderedSections: ReactNode[] = [];
  const pushUnique = (node: ReactNode) => {
    if (node) orderedSections.push(node);
  };

  if (focus === "documents") {
    pushUnique(intakeChecklist);
    pushUnique(termsSection);
    pushUnique(releaseSection);
    pushUnique(loanSection);
  } else if (focus === "terms") {
    pushUnique(termsSection);
    pushUnique(intakeChecklist);
    pushUnique(releaseSection);
    pushUnique(loanSection);
  } else if (focus === "release") {
    pushUnique(releaseSection);
    pushUnique(termsSection);
    pushUnique(loanSection);
    pushUnique(intakeChecklist);
  } else if (focus === "loan") {
    pushUnique(loanSection);
    pushUnique(releaseSection);
    pushUnique(termsSection);
    pushUnique(intakeChecklist);
  } else {
    pushUnique(termsSection);
    pushUnique(intakeChecklist);
    pushUnique(releaseSection);
    pushUnique(loanSection);
  }

  return (
    <div>
      <Breadcrumbs
        className="mb-3"
        items={[
          { label: "Dashboard", href: "/borrower" },
          { label: crumbLabel },
        ]}
      />
      <PageHeader title={pageTitle} description={pageDescription} />

      {error ? (
        <div className="mb-4">
          <Alert>{error}</Alert>
        </div>
      ) : null}

      <div className="banner warn mb-6">
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
          style={{ flexShrink: 0 }}
        >
          <circle cx="12" cy="12" r="10" />
          <path d="M12 16v-4M12 8h.01" />
        </svg>
        <span>
          <b>{guidance.title}</b>
          {" — "}
          {guidance.body}
        </span>
      </div>

      <section className="mb-6 overflow-hidden rounded-[var(--r-lg)] border border-line-soft bg-surface-2/70">
        <div className="border-b border-line-soft px-4 py-3 sm:px-5">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant={statusBadgeVariant(application.status)} dot>
                {application.statusLabel ??
                  formatStatusLabel(application.status)}
              </Badge>
              <Badge variant="neutral">
                {application.isReloan ? "Reloan" : "New loan"}
              </Badge>
            </div>
            <p className="text-xs text-ink-400">
              Updated {formatDateTime(application.updatedAt)}
            </p>
          </div>
          {blockerLabel ? (
            <p className="mt-2 max-w-full break-words text-sm leading-snug text-ink-700">
              <span className="font-medium text-warning">Hold reason:</span>{" "}
              {blockerLabel}
            </p>
          ) : null}
        </div>

        <div className="grid gap-3 px-4 py-4 sm:grid-cols-2 sm:px-5 lg:grid-cols-4">
          <div>
            <div className="text-[11px] font-semibold uppercase tracking-[0.06em] text-ink-400">
              Application no.
            </div>
            <div className="mono mt-1 text-sm font-semibold text-ink-900">
              {application.applicationNo ?? "Pending assignment"}
            </div>
          </div>
          <div>
            <div className="text-[11px] font-semibold uppercase tracking-[0.06em] text-ink-400">
              Filed
            </div>
            <div className="mono mt-1 text-sm font-semibold text-ink-900">
              {formatDate(application.createdAt)}
            </div>
          </div>
          <div>
            <div className="text-[11px] font-semibold uppercase tracking-[0.06em] text-ink-400">
              Loan type
            </div>
            <div className="mt-1 text-sm font-semibold text-ink-900">
              {computation?.loanTypeName ??
                (application.isReloan ? "Reloan" : "New loan")}
            </div>
          </div>
          <div>
            <div className="text-[11px] font-semibold uppercase tracking-[0.06em] text-ink-400">
              Principal
            </div>
            <div className="mono mt-1 text-sm font-semibold text-ink-900">
              {computation
                ? `₱${formatMoney(computation.principal)}`
                : "Not computed yet"}
            </div>
          </div>
        </div>

        {docsSummary && docsSummary.required > 0 ? (
          <div className="border-t border-line-soft px-4 py-4 sm:px-5">
            <div className="prog-lbl">
              <span>Intake documents</span>
              <b>
                {docsSummary.uploaded}/{docsSummary.required} · {docsPct}%
              </b>
            </div>
            <div className="prog">
              <i style={{ width: `${docsPct ?? 0}%` }} />
            </div>
            <p className="mt-2 text-xs text-ink-400">
              {docsSummary.complete} confirmed by staff ·{" "}
              {Math.max(docsSummary.required - docsSummary.uploaded, 0)} still
              missing
            </p>
          </div>
        ) : null}
      </section>

      <Card className="mb-6 overflow-x-auto">
        <h2 className="mb-3 font-display text-lg font-semibold text-navy-900">
          Your progress
        </h2>
        <BorrowerStatusTimeline currentStatus={application.status} />
        {recentHistory.length ? (
          <div className="mt-5 border-t border-[var(--line-soft)] pt-4">
            <p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.06em] text-ink-400">
              Recent updates
            </p>
            <ul className="flex flex-col gap-2">
              {recentHistory.map((entry, index) => (
                <li
                  key={`${entry.status}-${entry.at}-${index}`}
                  className="flex flex-wrap items-baseline justify-between gap-2 text-sm"
                >
                  <span className="font-medium text-ink-900">
                    {entry.label ?? formatStatusLabel(entry.status)}
                    {entry.note ? (
                      <span className="font-normal text-ink-500">
                        {" "}
                        · {entry.note}
                      </span>
                    ) : null}
                  </span>
                  <span className="mono text-xs text-ink-400">
                    {formatDateTime(entry.at)}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </Card>

      <div className="flex flex-col gap-6">{orderedSections}</div>

      {isDraft ? (
        <div className="mb-6 mt-6 flex flex-wrap items-center justify-between gap-3 rounded-[var(--r-lg)] border border-line-soft bg-surface-2/70 px-4 py-4 sm:px-5">
          <div>
            <p className="font-display text-base font-semibold text-navy-900">
              Ready to submit?
            </p>
            <p className="mt-1 text-sm text-ink-500">
              {docsSummary
                ? `This application is not yet visible to Loan Star. You can submit now and finish uploading documents afterward (${docsSummary.uploaded} of ${docsSummary.required} uploaded so far).`
                : "This application is not yet visible to Loan Star."}
            </p>
          </div>
          <Button
            type="button"
            disabled={!canSubmit}
            onClick={() => setShowSubmitConfirm(true)}
          >
            Submit application
          </Button>
        </div>
      ) : null}

      <ConfirmDialog
        open={showSubmitConfirm}
        title="Submit your application?"
        message="Once submitted, your application becomes visible to Loan Star and CSA will start reviewing it. You can still update your documents afterward if needed."
        confirmLabel="Yes, submit"
        cancelLabel="Cancel"
        loading={submitting}
        onConfirm={() => void handleSubmitApplication()}
        onCancel={() => setShowSubmitConfirm(false)}
      />
      {profile ? (
        <AutofillOverlay
          actions={[
            {
              label: "Fill Application Form",
              onClick: () =>
                setProfile(
                  fakeBorrowerProfile(
                    application?.segment ?? "seafarer",
                    application?.entityType ?? null,
                    profile,
                  ),
                ),
            },
          ]}
        />
      ) : null}
    </div>
  );
}
