import type { ChecklistItem } from "@/lib/documents/checklist";

import { isAutoGeneratedDocumentSlug } from "./constants";

export type CombinedUploadTarget = {
  documentTypeId: string;
  documentTypeSlug: string;
  documentTypeName: string;
  stage: string;
};

/**
 * Required, non-auto-generated document types across the signing-stage
 * card (auto-generated PDFs excluded, same as the frontend's
 * excludeSlugs) and the release checklist card (no exclusions) — the
 * exact set the combined upload satisfies in one shot.
 */
export function resolveCombinedUploadTargets(
  signingStageItems: ChecklistItem[],
  releaseItems: ChecklistItem[],
  signingStage: string,
): CombinedUploadTarget[] {
  const targets = new Map<string, CombinedUploadTarget>();
  for (const item of signingStageItems) {
    if (!item.isRequired) continue;
    if (isAutoGeneratedDocumentSlug(item.documentTypeSlug)) continue;
    targets.set(item.documentTypeId, {
      documentTypeId: item.documentTypeId,
      documentTypeSlug: item.documentTypeSlug,
      documentTypeName: item.documentTypeName,
      stage: signingStage,
    });
  }
  for (const item of releaseItems) {
    if (!item.isRequired) continue;
    targets.set(item.documentTypeId, {
      documentTypeId: item.documentTypeId,
      documentTypeSlug: item.documentTypeSlug,
      documentTypeName: item.documentTypeName,
      stage: "release",
    });
  }
  return Array.from(targets.values());
}
