/** Element type for `release_files.release_paths` / `masterlist.release_paths` (`ReleasePath[]`). */
export type ReleasePath = "with_pdc" | "without_pdc";

export type ReleaseFileStatus =
  | "awaiting_path"
  | "pdc_encoding"
  | "ready_generate"
  | "awaiting_signatures"
  | "awaiting_briefing"
  | "ready_release"
  | "released"
  | "closed";

export const AUTO_GENERATED_SLUGS: Record<ReleasePath, string[]> = {
  with_pdc: [
    "blri",
    "promissory_note",
    "disclosure_statement",
    "letter_of_intent",
    "loan_agreement",
    "check_voucher",
    "ar_check_voucher",
  ],
  without_pdc: [
    "blri",
    "promissory_note",
    "disclosure_statement",
    "letter_of_intent",
    "loan_agreement",
    "cash_voucher",
    "ar_atm_voucher",
  ],
};

/**
 * Collateral-gated release documents (Phase 10) — generated in addition to
 * the path-based slugs above when the application carries that collateral
 * type. Path-independent (same content regardless of with_pdc/without_pdc),
 * so they're unioned in separately rather than added to AUTO_GENERATED_SLUGS.
 */
export const COLLATERAL_GENERATED_SLUGS: Record<"car_refinancing" | "real_estate", string[]> = {
  car_refinancing: ["deed_of_chattel_mortgage"],
  real_estate: ["real_estate_mortgage"],
};

/** Union of auto-generated slugs across both release paths, plus collateral-gated slugs. */
export function allAutoGeneratedSlugs(): Set<string> {
  return new Set([
    ...AUTO_GENERATED_SLUGS.with_pdc,
    ...AUTO_GENERATED_SLUGS.without_pdc,
    ...COLLATERAL_GENERATED_SLUGS.car_refinancing,
    ...COLLATERAL_GENERATED_SLUGS.real_estate,
  ]);
}

export function isAutoGeneratedDocumentSlug(slug: string): boolean {
  return allAutoGeneratedSlugs().has(slug);
}

export const BLOCKER_BY_STATUS: Record<ReleaseFileStatus, string> = {
  awaiting_path: "Pending: release path selection",
  pdc_encoding: "Pending: PDC not yet submitted",
  ready_generate: "Pending: document generation",
  awaiting_signatures: "Pending: document signatures",
  awaiting_briefing: "Documents signed, awaiting briefing",
  ready_release: "Documents signed, awaiting check release",
  released: "Released",
  closed: "Released — transmitted to main branch",
};

export function releaseStageForPath(path: ReleasePath): string {
  return path === "with_pdc" ? "signing_with_pdc" : "signing_without_pdc";
}

/** All signing checklist stages for the selected release path(s). */
export function releaseStagesForPaths(paths: ReleasePath[]): string[] {
  return paths.map(releaseStageForPath);
}

export function readyReleaseBlocker(paths: ReleasePath[] | null): string {
  if (paths == null) {
    return BLOCKER_BY_STATUS.ready_release;
  }
  const hasWithPdc = paths.includes("with_pdc");
  const hasWithoutPdc = paths.includes("without_pdc");
  if (hasWithPdc && hasWithoutPdc) {
    return "Documents signed, awaiting check and cash release";
  }
  if (hasWithoutPdc) {
    return "Documents signed, awaiting cash release";
  }
  return BLOCKER_BY_STATUS.ready_release;
}

/** Release is allowed only when briefing was click-signed by the borrower. */
export function canRecordRelease(
  releaseStatus: ReleaseFileStatus,
  briefingAcknowledgedAt: string | null | undefined,
): boolean {
  return releaseStatus === "ready_release" && Boolean(briefingAcknowledgedAt);
}
