import type { ReleasePath } from "./constants";

/**
 * Per-segment eligibility for a release document, set by an admin on the
 * template (see migration `*_release_template_generation_eligibility`).
 *
 * - `always`   — part of the "Generate all" set (still subject to the code
 *                conditions below and to having a published version).
 * - `optional` — offered in the LRA generate picker, not auto-generated.
 * - `hidden`   — not offered for that segment at all.
 */
export type GenEligibility = "always" | "optional" | "hidden";

/** Segment groups that share a document list. `individual` follows `sme`. */
export type SegmentGroup = "seafarer" | "sme";

export type CollateralType = "none" | "car_refinancing" | "real_estate" | null;

export type ReleaseTemplateRow = {
  slug: string;
  name: string;
  publishedVersionNo: number | null;
  seafarerGeneration: GenEligibility;
  smeGeneration: GenEligibility;
};

/**
 * Voucher slugs that belong to exactly one release path. Copied verbatim from
 * the retired `constants.ts` `AUTO_GENERATED_SLUGS` split — the path no longer
 * *filters* the generated set, it only narrows the voucher pair (path is logic,
 * not an admin preference).
 */
export const PATH_SPECIFIC_SLUGS: Record<ReleasePath, readonly string[]> = {
  with_pdc: [
    "check_voucher",
    "ar_check_voucher",
    "check_voucher_sf",
    "ar_check_voucher_sf",
    "ar_multiple_check_sf",
  ],
  without_pdc: [
    "cash_voucher",
    "ar_atm_voucher",
    "cash_voucher_sf",
    "ar_atm_voucher_sf",
    "ar_cash_voucher_sf",
  ],
};

/**
 * Seafarer-only copies of the release documents whose client source differs
 * from the SME one (SF Calculator.xlsm tabs + SFCalculator Word files — see
 * docs/document-fidelity/sf-template-tracker.md). Each is its own template row
 * with `sme_generation = 'hidden'`; the un-suffixed slug stays the SME version.
 */
export const SF_RELEASE_SLUGS: readonly string[] = [
  "blri_sf",
  "promissory_note_sf",
  "disclosure_statement_sf",
  "check_voucher_sf",
  "ar_check_voucher_sf",
  "cash_voucher_sf",
  "ar_atm_voucher_sf",
  "ar_cash_voucher_sf",
  "ar_multiple_check_sf",
  "loan_information_sf",
  "payment_details_sf",
];

/**
 * The client has one loan agreement per payment arrangement. Exactly one of
 * these applies to a loan, chosen by the computation's payment frequency:
 * the standard agreement for everything not listed here.
 */
const LOAN_AGREEMENT_BY_FREQUENCY: Record<string, string> = {
  bi_monthly: "loan_agreement_bi_monthly",
  daily: "loan_agreement_per_day",
  quarterly: "loan_agreement_vienovo",
  quarterly_special: "loan_agreement_vienovo",
  two_monthly: "loan_agreement_vienovo",
  two_monthly_special: "loan_agreement_vienovo",
};
const LOAN_AGREEMENT_SLUGS: ReadonlySet<string> = new Set([
  "loan_agreement",
  ...Object.values(LOAN_AGREEMENT_BY_FREQUENCY),
]);

/** The loan agreement template that applies to a loan with this payment frequency. */
export function loanAgreementSlugFor(paymentFrequency: string | null | undefined): string {
  return LOAN_AGREEMENT_BY_FREQUENCY[paymentFrequency ?? ""] ?? "loan_agreement";
}

const COLLATERAL_SLUG: Record<"car_refinancing" | "real_estate", string> = {
  car_refinancing: "deed_of_chattel_mortgage",
  real_estate: "real_estate_mortgage",
};

/**
 * Every `category = 'release'` template slug. Equals the old
 * `allAutoGeneratedSlugs()` union (both paths + both collateral types) plus the
 * three slugs that were never in the auto set. Used to hide release-packet docs
 * from the manual upload / borrower checklist surfaces — same semantic as the
 * retired `isAutoGeneratedDocumentSlug`.
 */
export const RELEASE_DOCUMENT_SLUGS: ReadonlySet<string> = new Set<string>([
  "blri",
  "promissory_note",
  "disclosure_statement",
  "letter_of_intent",
  "loan_agreement",
  ...PATH_SPECIFIC_SLUGS.with_pdc,
  ...PATH_SPECIFIC_SLUGS.without_pdc,
  COLLATERAL_SLUG.car_refinancing,
  COLLATERAL_SLUG.real_estate,
  "acknowledgement_receipt",
  "ar_cash_voucher",
  "endorsement_letter",
  ...SF_RELEASE_SLUGS,
  ...Object.values(LOAN_AGREEMENT_BY_FREQUENCY),
]);

export function segmentGroup(
  segment: "seafarer" | "sme" | "individual",
): SegmentGroup {
  return segment === "seafarer" ? "seafarer" : "sme";
}

/**
 * Does this template's path / collateral condition match this loan? This is the
 * logic that stays in code — the admin eligibility flags gate *whether* a doc is
 * offered, these conditions gate *which* one applies to a given release.
 */
export function templateConditionMatches(
  slug: string,
  releasePaths: ReleasePath[],
  collateralType: CollateralType,
  paymentFrequency?: string | null,
): boolean {
  if (LOAN_AGREEMENT_SLUGS.has(slug)) {
    return slug === loanAgreementSlugFor(paymentFrequency);
  }
  if (PATH_SPECIFIC_SLUGS.with_pdc.includes(slug)) {
    return releasePaths.includes("with_pdc");
  }
  if (PATH_SPECIFIC_SLUGS.without_pdc.includes(slug)) {
    return releasePaths.includes("without_pdc");
  }
  if (slug === COLLATERAL_SLUG.car_refinancing) {
    return collateralType === "car_refinancing";
  }
  if (slug === COLLATERAL_SLUG.real_estate) {
    return collateralType === "real_estate";
  }
  return true;
}

export type ReleaseDocumentCandidate = {
  slug: string;
  name: string;
  eligibility: GenEligibility;
  /** A published template version exists — required before it can be generated. */
  canGenerate: boolean;
};

/**
 * Canonical display order for the generate picker — the core packet first (in
 * signing order), then the path vouchers, then everything else alphabetically.
 */
const PICKER_ORDER: readonly string[] = [
  "loan_information_sf",
  "blri",
  "blri_sf",
  "promissory_note",
  "promissory_note_sf",
  "disclosure_statement",
  "disclosure_statement_sf",
  "letter_of_intent",
  "loan_agreement",
  "loan_agreement_bi_monthly",
  "loan_agreement_per_day",
  "loan_agreement_vienovo",
  "check_voucher",
  "check_voucher_sf",
  "ar_check_voucher",
  "ar_check_voucher_sf",
  "cash_voucher",
  "cash_voucher_sf",
  "ar_atm_voucher",
  "ar_atm_voucher_sf",
  "ar_cash_voucher",
  "ar_cash_voucher_sf",
  "ar_multiple_check_sf",
  "payment_details_sf",
  "deed_of_chattel_mortgage",
  "real_estate_mortgage",
  "acknowledgement_receipt",
  "endorsement_letter",
];

function pickerRank(slug: string): number {
  const i = PICKER_ORDER.indexOf(slug);
  return i === -1 ? PICKER_ORDER.length : i;
}

/**
 * Rows to show in the generate modal for this loan: not `hidden` for the
 * segment group, and matching the loan's path / collateral condition. Ordered
 * by `PICKER_ORDER` then name.
 */
export function releaseDocumentCandidates(
  group: SegmentGroup,
  catalog: ReleaseTemplateRow[],
  releasePaths: ReleasePath[],
  collateralType: CollateralType,
  paymentFrequency?: string | null,
): ReleaseDocumentCandidate[] {
  const out: ReleaseDocumentCandidate[] = [];
  for (const row of catalog) {
    const eligibility =
      group === "seafarer" ? row.seafarerGeneration : row.smeGeneration;
    if (eligibility === "hidden") continue;
    if (!templateConditionMatches(row.slug, releasePaths, collateralType, paymentFrequency)) {
      continue;
    }
    out.push({
      slug: row.slug,
      name: row.name,
      eligibility,
      canGenerate: row.publishedVersionNo != null,
    });
  }
  out.sort(
    (a, b) => pickerRank(a.slug) - pickerRank(b.slug) || a.name.localeCompare(b.name),
  );
  return out;
}

/**
 * Slugs produced by "Generate all" — `always` for the group, condition-matched,
 * and publishable. For a seafarer loan this reproduces the old
 * `AUTO_GENERATED_SLUGS[path]` set exactly (see the seed migration + tests).
 */
export function autoGenerateSlugs(
  group: SegmentGroup,
  catalog: ReleaseTemplateRow[],
  releasePaths: ReleasePath[],
  collateralType: CollateralType,
  paymentFrequency?: string | null,
): string[] {
  return releaseDocumentCandidates(group, catalog, releasePaths, collateralType, paymentFrequency)
    .filter((c) => c.eligibility === "always" && c.canGenerate)
    .map((c) => c.slug);
}

// ---------------------------------------------------------------------------
// Generate-modal picker: server-side search / filter / pagination
// ---------------------------------------------------------------------------

/** One row in the generate modal — a candidate joined to what's been generated. */
export type PickerItem = ReleaseDocumentCandidate & {
  generated: {
    documentId: string;
    generatedAt: string;
    signedAt: string | null;
    isFinalized: boolean;
    downloadUrl: string | null;
  } | null;
};

export type PickerEligibilityFilter = "all" | "required" | "optional";
export type PickerStatusFilter =
  | "all"
  | "not_generated"
  | "generated"
  | "signed";

export type PickerQuery = {
  search?: string;
  eligibility?: PickerEligibilityFilter;
  status?: PickerStatusFilter;
  /** Accepts a raw query-string value; coerced and clamped. */
  page?: number | string | null;
  pageSize?: number | string | null;
};

export type PickerPage = {
  items: PickerItem[];
  total: number;
  page: number;
  pageCount: number;
  pageSize: number;
};

export const PICKER_ELIGIBILITY_FILTERS: readonly PickerEligibilityFilter[] = [
  "all",
  "required",
  "optional",
];
export const PICKER_STATUS_FILTERS: readonly PickerStatusFilter[] = [
  "all",
  "not_generated",
  "generated",
  "signed",
];

function coerceInt(value: unknown, fallback: number): number {
  const n = Math.trunc(Number(value));
  return Number.isFinite(n) ? n : fallback;
}

/**
 * Pure: apply search + requirement/status filters, then paginate. `all` is
 * assumed already ordered (by `releaseDocumentCandidates`). Unknown filter
 * values fall back to `"all"`. `page` is clamped into `[1, pageCount]`.
 */
export function queryPickerItems(all: PickerItem[], q: PickerQuery): PickerPage {
  const search = (q.search ?? "").trim().toLowerCase();
  const eligibility = PICKER_ELIGIBILITY_FILTERS.includes(
    q.eligibility as PickerEligibilityFilter,
  )
    ? (q.eligibility as PickerEligibilityFilter)
    : "all";
  const status = PICKER_STATUS_FILTERS.includes(q.status as PickerStatusFilter)
    ? (q.status as PickerStatusFilter)
    : "all";
  const pageSize = Math.min(Math.max(coerceInt(q.pageSize, 6), 1), 50);

  const filtered = all.filter((it) => {
    if (
      search &&
      !it.name.toLowerCase().includes(search) &&
      !it.slug.toLowerCase().includes(search)
    ) {
      return false;
    }
    if (eligibility === "required" && it.eligibility !== "always") return false;
    if (eligibility === "optional" && it.eligibility !== "optional") return false;
    if (status === "not_generated" && it.generated) return false;
    if (status === "generated" && (!it.generated || it.generated.signedAt)) {
      return false;
    }
    if (status === "signed" && !it.generated?.signedAt) return false;
    return true;
  });

  const total = filtered.length;
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  const page = Math.min(Math.max(coerceInt(q.page, 1), 1), pageCount);
  const start = (page - 1) * pageSize;

  return {
    items: filtered.slice(start, start + pageSize),
    total,
    page,
    pageCount,
    pageSize,
  };
}
