import test from "node:test";
import assert from "node:assert/strict";

import {
  allAutoGeneratedSlugs,
  isAutoGeneratedDocumentSlug,
} from "../constants";

test("allAutoGeneratedSlugs unions both release paths", () => {
  const slugs = allAutoGeneratedSlugs();
  assert.ok(slugs.has("promissory_note"));
  assert.ok(slugs.has("blri"));
  assert.ok(slugs.has("check_voucher"));
  assert.ok(slugs.has("cash_voucher"));
  assert.ok(slugs.has("ar_check_voucher"));
  assert.ok(slugs.has("ar_atm_voucher"));
  assert.ok(!slugs.has("ar_cash_voucher"));
  assert.ok(slugs.has("letter_of_intent"));
  assert.ok(slugs.has("loan_agreement"));
});

test("isAutoGeneratedDocumentSlug identifies LRA-generated types", () => {
  assert.equal(isAutoGeneratedDocumentSlug("promissory_note"), true);
  assert.equal(isAutoGeneratedDocumentSlug("letter_of_intent"), true);
  assert.equal(isAutoGeneratedDocumentSlug("loan_agreement"), true);
  assert.equal(isAutoGeneratedDocumentSlug("affidavit_understanding"), false);
  assert.equal(isAutoGeneratedDocumentSlug("bank_authorization"), false);
});
