import test from "node:test";
import assert from "node:assert/strict";

import {
  allAutoGeneratedSlugs,
  COLLATERAL_GENERATED_SLUGS,
  isAutoGeneratedDocumentSlug,
} from "../constants";

test("allAutoGeneratedSlugs unions both release paths", () => {
  const slugs = allAutoGeneratedSlugs();
  assert.ok(slugs.has("promissory_note"));
  assert.ok(slugs.has("blri"));
  assert.ok(slugs.has("check_voucher"));
  assert.ok(slugs.has("cash_voucher"));
  assert.ok(slugs.has("ar_check_voucher"));
  assert.ok(slugs.has("ar_atm_voucher"));
  assert.ok(!slugs.has("ar_cash_voucher"));
  assert.ok(slugs.has("letter_of_intent"));
  assert.ok(slugs.has("loan_agreement"));
});

test("isAutoGeneratedDocumentSlug identifies LRA-generated types", () => {
  assert.equal(isAutoGeneratedDocumentSlug("promissory_note"), true);
  assert.equal(isAutoGeneratedDocumentSlug("letter_of_intent"), true);
  assert.equal(isAutoGeneratedDocumentSlug("loan_agreement"), true);
  assert.equal(isAutoGeneratedDocumentSlug("affidavit_understanding"), false);
  assert.equal(isAutoGeneratedDocumentSlug("bank_authorization"), false);
});

test("COLLATERAL_GENERATED_SLUGS (Phase 10) is gated by collateral type only", () => {
  assert.deepEqual(COLLATERAL_GENERATED_SLUGS.car_refinancing, [
    "deed_of_chattel_mortgage",
  ]);
  assert.deepEqual(COLLATERAL_GENERATED_SLUGS.real_estate, [
    "real_estate_mortgage",
  ]);
});

test("allAutoGeneratedSlugs also includes collateral-gated slugs", () => {
  const slugs = allAutoGeneratedSlugs();
  assert.ok(slugs.has("deed_of_chattel_mortgage"));
  assert.ok(slugs.has("real_estate_mortgage"));
});

test("isAutoGeneratedDocumentSlug recognizes collateral-gated slugs", () => {
  assert.equal(isAutoGeneratedDocumentSlug("deed_of_chattel_mortgage"), true);
  assert.equal(isAutoGeneratedDocumentSlug("real_estate_mortgage"), true);
});
