-- ===========================================================================
-- Phase 5 — Document Template System: decouple from the release flow
--
-- See docs/document-template-system-plan.md §4 "Phase 5".
--
-- `rendered_documents` is the general-purpose sibling of `generated_documents`.
-- The existing release docs stay on `generated_documents` (proven, RLS-covered);
-- this table is only for NEW, non-release documents (Demand Letter, Endorsement
-- Letter, Acknowledgement Receipt, Final Computation Sheet, ...) that any stage
-- can produce. No existing rows are migrated.
--
-- Keyed by `loan_application_id` (the stable spine) with an OPTIONAL
-- `release_file_id` for docs that do belong to a release. Every row records the
-- `template_version_id` it was rendered from (audit/version pinning) and the
-- `module` that owns it — the module is what RLS gates read/write against, so a
-- document generated by, e.g., collection is only writable by collection editors
-- but stays readable per that module's view permission and by the borrower.
--
-- Additive & dormant: nothing writes here until the Phase 5 helper is called
-- from a stage in Phase 6. Zero behavior change to the release flow.
-- ===========================================================================

CREATE TABLE public.rendered_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_application_id uuid NOT NULL
    REFERENCES public.loan_applications(id) ON DELETE CASCADE,
  -- Optional: set when the document is tied to a specific release file. Kept as
  -- SET NULL so purging a release file never destroys the audit row of a doc
  -- that was already rendered (the PDF bytes are frozen in storage anyway).
  release_file_id uuid
    REFERENCES public.release_files(id) ON DELETE SET NULL,
  -- The module that owns this document (e.g. 'collection', 'release_lra',
  -- 'accounting_ar'). RLS gates read/write against this via has_module_permission.
  module text NOT NULL,
  document_slug text NOT NULL,
  -- Which published template version produced this doc. Nullable + SET NULL so
  -- purging a template version never destroys an already-rendered audit row.
  template_version_id uuid
    REFERENCES public.document_template_versions(id) ON DELETE SET NULL,
  storage_path text NOT NULL,
  content_hash text NOT NULL,
  -- Optional signing/finalization columns (mirror generated_documents so a
  -- non-release doc can also be frozen/signed if a stage needs it).
  is_finalized boolean NOT NULL DEFAULT false,
  finalized_at timestamptz,
  signed_at timestamptz,
  signed_by uuid REFERENCES auth.users(id),
  signature_hash text,
  generated_by uuid REFERENCES auth.users(id),
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.rendered_documents IS
  'General-purpose rendered documents keyed by loan_application_id (optional release_file_id). Sibling of generated_documents for NON-release documents. `module` is the RLS ownership key.';

CREATE INDEX idx_rendered_documents_application
  ON public.rendered_documents(loan_application_id);

CREATE INDEX idx_rendered_documents_app_slug
  ON public.rendered_documents(loan_application_id, document_slug);

CREATE TRIGGER rendered_documents_updated_at
  BEFORE UPDATE ON public.rendered_documents
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS — per owning module (recurring gap pattern in this repo; policies are in
-- the same migration as the table).
--   * SELECT: super admin, any staffer with 'view' on the owning module, or the
--     borrower who owns the application.
--   * INSERT: super admin, or a staffer with 'edit' on the module they claim
--     (WITH CHECK prevents claiming a module you cannot edit).
--   * UPDATE: only while not finalized; super admin or module 'edit'. WITH CHECK
--     keeps rows from being flipped back out of the finalized state elsewhere.
--   * DELETE: no policy = denied (documents are an audit trail).
-- ---------------------------------------------------------------------------
ALTER TABLE public.rendered_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY rendered_documents_select ON public.rendered_documents
  FOR SELECT TO authenticated
  USING (
    public.is_super_admin()
    OR public.has_module_permission(module, 'view')
    OR EXISTS (
      SELECT 1 FROM public.loan_applications la
      JOIN public.borrowers b ON b.id = la.borrower_id
      WHERE la.id = loan_application_id AND b.user_id = auth.uid()
    )
  );

CREATE POLICY rendered_documents_insert ON public.rendered_documents
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_super_admin()
    OR public.has_module_permission(module, 'edit')
  );

CREATE POLICY rendered_documents_update ON public.rendered_documents
  FOR UPDATE TO authenticated
  USING (
    is_finalized = false
    AND (
      public.is_super_admin()
      OR public.has_module_permission(module, 'edit')
    )
  )
  WITH CHECK (is_finalized = false);
