-- Phase 2.2 RECONCILIATION — client sign-off received 2026-08-07.
--
-- Authoritative source: "LIST OF REQUIREMENTS.pdf"
--   (Downloads\SYSTEM DEV\Step 1 - Processing-CSA\SME - Individual\)
--   header: "LOAN STAR LENDING GROUP CORP. (non collateral) / LSLG FINANCING CORP (collateral loan)"
--   section: "REQUIREMENTS FOR SME ( BUSINESS ) LOAN"
--
-- The original Phase 2.2 seed was built from the application forms' embedded fine
-- print (an operator decision, explicitly flagged as pending client sign-off).
-- The client's actual requirements list adds 7 documents that were missing —
-- including the core credit documents (bank statements, ITR, financial statements)
-- — and defines a different entity-type split.
--
-- ADDITIVE ONLY. Nothing is deleted (Hard Constraint #6). Slugs seeded earlier but
-- absent from the client list (tin_ctc, location_sketch, board_resolution,
-- secretary_certificate) are LEFT IN PLACE and flagged in the Progress Log for a
-- separate client decision — they came from the application forms' own fine print,
-- so they may still be legitimate.
--
-- Note: "Completely filled out application form" (both columns, item 9) is already
-- handled — `application_form` is auto-generated by the document-template system,
-- and its upload slot was deliberately retired in 20260715030000.

INSERT INTO public.document_types (slug, name) VALUES
  ('bank_statement_6mo',        '6 Months Latest Bank Statement'),
  ('itr_with_fs',               'ITR with Financial Statements'),
  ('financial_statements',      'Financial Statements (2 Years Latest + In-House Interim)'),
  ('proof_of_billing',          'Proof of Billing'),
  ('business_picture',          'Picture of Business'),
  ('articles_of_incorporation', 'Articles of Incorporation and By-Laws'),
  ('company_profile',           'Company Profile')
ON CONFLICT (slug) DO NOTHING;

-- Common to BOTH Sole Proprietorship and Partnership/Corporation.
-- Sole prop items 2, 5, 10 · Corporate items 4, 3, 10.
INSERT INTO public.stage_checklists (
  stage, document_type_id, is_required, is_optional_flag, sort_order, segment, entity_type
)
SELECT 'intake', dt.id, true, false, t.ord, 'sme', NULL
FROM public.document_types dt
JOIN (
  VALUES
    ('bank_statement_6mo',   14),
    ('itr_with_fs',          15),
    ('financial_statements', 16)
) AS t(slug, ord) ON dt.slug = t.slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.stage_checklists sc
  WHERE sc.stage = 'intake'
    AND sc.document_type_id = dt.id
    AND sc.segment = 'sme'
    AND sc.entity_type IS NULL
);

-- SOLE PROPRIETORSHIP only (client list items 4 and 7).
-- First individual-only rows in the system — the original seed had none.
INSERT INTO public.stage_checklists (
  stage, document_type_id, is_required, is_optional_flag, sort_order, segment, entity_type
)
SELECT 'intake', dt.id, true, false, t.ord, 'sme', 'individual'
FROM public.document_types dt
JOIN (
  VALUES
    ('proof_of_billing', 17),
    ('business_picture', 18)
) AS t(slug, ord) ON dt.slug = t.slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.stage_checklists sc
  WHERE sc.stage = 'intake'
    AND sc.document_type_id = dt.id
    AND sc.segment = 'sme'
    AND sc.entity_type = 'individual'
);

-- PARTNERSHIP / CORPORATION only (client list items 2 and 8).
INSERT INTO public.stage_checklists (
  stage, document_type_id, is_required, is_optional_flag, sort_order, segment, entity_type
)
SELECT 'intake', dt.id, true, false, t.ord, 'sme', 'corporate'
FROM public.document_types dt
JOIN (
  VALUES
    ('articles_of_incorporation', 19),
    ('company_profile',           20)
) AS t(slug, ord) ON dt.slug = t.slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.stage_checklists sc
  WHERE sc.stage = 'intake'
    AND sc.document_type_id = dt.id
    AND sc.segment = 'sme'
    AND sc.entity_type = 'corporate'
);
